title: Agorava
gem_version: 0.5.0
google_analytics: UA-31280631-1
disqus: agoravablog
base_url: http://agorava.org/

profiles:
  development:
    disqus_developer: true
  production:
    base_url: http://www.agorava.org/
    disqus_generate_id: true
    deploy:
      host: github_pages
      branch: master

