title: Agorava
gem_version: 0.5.0

profiles:
  development:
    disqus_developer: true
  production:
    base_url: http://agorava.org/
    disqus_generate_id: true
    google_analytics: UA-31280631-1
    deploy:
      host: github_pages
      branch: master
disqus: agoravablog
base_url: http://agorava.org
