title: Agorava
gem_version: 0.5.0
disqus: agoravablog

profiles:
  development:
    disqus_developer: true
  production:
    base_url: http://agorava.org/
    google_analytics: UA-31280631-1
    disqus_generate_id: true
    deploy:
      host: github_pages
      branch: master

